language: c++
dist: trusty
compiler: g++
sudo: required

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - cmake
     #- gcc-9
     #- g++-9
#     - qtbase5-dev
#     - libqt5opengl5-dev
     - libboost-dev
     - libboost-regex-dev
     - libboost-system-dev
     - libboost-program-options-dev
     - libboost-filesystem-dev
     - libboost-iostreams-dev
     - libeigen3-dev
     - libmysqlclient-dev
     - libmysql++-dev
     - libsqlite3-dev
     - liblog4cpp5-dev
     - libgdal-dev
     - libarchive-dev
     - libtbb-dev

compiler:
 - gcc
# - clang

before_install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt58-trusty
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get -q update


install:
 - sudo apt-get --only-upgrade install libgdal-dev
#qt
 - sudo apt-get install qt58base qt58charts-no-lgpl # qt58svg qt58charts-no-lgpl qt58xmlpatterns
 - source /opt/qt58/bin/qt58-env.sh
# NemaTode install
 - wget https://github.com/ckgt/NemaTode/archive/master.zip
 - unzip master.zip
 - mkdir NemaTode-master/build
 - cd NemaTode-master/build && cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release .. && make && sudo make install
 - cd ../..
 
script:
 #- export CC=gcc-9
 #- export CXX=g++-9

 #build
 - mkdir build
 - cd build
 - cmake ..
 - cmake --build . -- -j2

